id: dbt_model
namespace: dev

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      dbt Model: "dbt Model Execution"

  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/Jessie2019W/BTC-Return-Stablecoin-Volume-Analysis
    branch: main
    namespace: "{{flow.namespace}}"
    gitDirectory: dbt/btc_analysis
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    description: "Execute dbt build (includes run and test)"
    containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    namespaceFiles:
      enabled: true
    env:
      DBT_DATABASE: "{{ kv('GCP_PROJECT_ID') }}"
      DBT_SCHEMA: "prod_dataset" # Dataset where transformed data is stored
    inputFiles:
      gcp_key.json: "{{ kv('GCP_CREDS') }}"
    commands:
      - dbt deps
      - dbt build
    profiles: |
      default:
        outputs:
          dev:
            type: bigquery
            method: service-account
            project: "{{ kv('GCP_PROJECT_ID') }}"
            dataset: "prod_dataset"
            location: "US"
            keyfile: gcp_key.json
            threads: 4
            timeout_seconds: 300
            priority: interactive
        target: dev

triggers:
  - id: on_either_pipeline_success
    type: io.kestra.plugin.core.trigger.Flow
    description: "Automatically trigger when either history_data_pipeline or crypto_market_data_pipeline flow succeeds"
    conditions:
      # This condition ensures that only successful executions are considered
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in: [SUCCESS]
      # This 'Or' condition checks if the successful execution is either of the specified flows
      - type: io.kestra.plugin.core.condition.Or
        conditions:
          - type: io.kestra.plugin.core.condition.ExecutionFlow
            namespace: dev
            flowId: history_data_pipeline
          - type: io.kestra.plugin.core.condition.ExecutionFlow
            namespace: dev
            flowId: crypto_market_data_pipeline

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{ kv('GCP_CREDS') }}"
      projectId: "{{ kv('GCP_PROJECT_ID') }}"